version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: federated_pneumonia_detection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5123:5123"

  postgrest:
    image: postgrest/postgrest
    restart: always
    environment:
      PGRST_DB_URI: "postgres://postgres:postgres@db:5123/federated_pneumonia_detection"
      PGRST_DB_SCHEMA: "public" # Or your specific schema
      PGRST_DB_ANON_ROLE: "postgres" # A role for anonymous users
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: