services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_DB: federated_pneumonia_detection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5123:5432"  # Expose container port 5432 at host port 5123

  postgrest:
    image: postgrest/postgrest
    restart: always
    environment:
      PGRST_DB_URI: "postgresql://postgres:postgres@db:5432/federated_pneumonia_detection"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "postgres"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
