"""empty message

Revision ID: 8252e1e6c4d3
Revises: 7036676c922c
Create Date: 2026-01-27 00:15:35.449389+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8252e1e6c4d3'
down_revision: Union[str, None] = '7036676c922c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes to upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_cmetadata_gin'),
        table_name='langchain_pg_embedding',
        postgresql_ops={'cmetadata': 'jsonb_path_ops'},
        postgresql_using='gin',
    )
    op.drop_table('langchain_pg_embedding')
    op.drop_table('langchain_pg_collection')
    op.drop_index(
        op.f('idx_message_store_session_id'),
        table_name='message_store',
    )
    op.drop_table('message_store')
    op.create_index(
        'ix_client_run_identifier',
        'clients',
        ['run_id', 'client_identifier'],
        unique=False,
    )
    op.create_index(
        op.f('ix_clients_run_id'),
        'clients',
        ['run_id'],
        unique=False,
    )
    op.create_unique_constraint(
        'uq_run_client',
        'clients',
        ['run_id', 'client_identifier'],
    )
    op.create_index(
        'ix_round_client_number',
        'rounds',
        ['client_id', 'round_number'],
        unique=False,
    )
    op.create_index(
        op.f('ix_rounds_client_id'),
        'rounds',
        ['client_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_rounds_round_number'),
        'rounds',
        ['round_number'],
        unique=False,
    )
    op.create_unique_constraint(
        'uq_client_round',
        'rounds',
        ['client_id', 'round_number'],
    )
    op.create_index(
        'ix_metric_run_round',
        'run_metrics',
        ['run_id', 'round_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_run_metrics_round_id'),
        'run_metrics',
        ['round_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_run_metrics_run_id'),
        'run_metrics',
        ['run_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_runs_start_time'),
        'runs',
        ['start_time'],
        unique=False,
    )
    op.create_index(
        op.f('ix_runs_status'),
        'runs',
        ['status'],
        unique=False,
    )
    op.create_index(
        op.f('ix_runs_training_mode'),
        'runs',
        ['training_mode'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes to downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_training_mode'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_start_time'), table_name='runs')
    op.drop_index(op.f('ix_run_metrics_run_id'), table_name='run_metrics')
    op.drop_index(op.f('ix_run_metrics_round_id'), table_name='run_metrics')
    op.drop_index('ix_metric_run_round', table_name='run_metrics')
    op.drop_constraint('uq_client_round', 'rounds', type_='unique')
    op.drop_index(op.f('ix_rounds_round_number'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_client_id'), table_name='rounds')
    op.drop_index('ix_round_client_number', table_name='rounds')
    op.drop_constraint('uq_run_client', 'clients', type_='unique')
    op.drop_index(op.f('ix_clients_run_id'), table_name='clients')
    op.drop_index('ix_client_run_identifier', table_name='clients')
    op.create_table(
        'message_store',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'message',
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('message_store_pkey')),
    )
    op.create_index(
        op.f('idx_message_store_session_id'),
        'message_store',
        ['session_id'],
        unique=False,
    )
    op.create_table(
        'langchain_pg_collection',
        sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'cmetadata',
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_collection_pkey')),
        sa.UniqueConstraint(
            'name',
            name=op.f('langchain_pg_collection_name_key'),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        'langchain_pg_embedding',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
        sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
        sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            'cmetadata',
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ['collection_id'],
            ['langchain_pg_collection.uuid'],
            name=op.f('langchain_pg_embedding_collection_id_fkey'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('langchain_pg_embedding_pkey')),
    )
    op.create_index(
        op.f('ix_cmetadata_gin'),
        'langchain_pg_embedding',
        ['cmetadata'],
        unique=False,
        postgresql_ops={'cmetadata': 'jsonb_path_ops'},
        postgresql_using='gin',
    )
    # ### end Alembic commands ###
