color_mode: RGB
config: !!python/object:federated_pneumonia_detection.models.experiment_config.ExperimentConfig
  adaptive_histogram: false
  augmentation_strength: 1.0
  base_path: .
  batch_size: 512
  checkpoint_dir: models/checkpoints
  clients_per_round: 3
  clip_limit: 2.0
  color_mode: RGB
  contrast_stretch: true
  device: cuda
  dropout_rate: 0.3
  early_stopping_patience: 7
  edge_enhancement: false
  edge_strength: 1.0
  epochs: 15
  fine_tune_layers_count: 0
  freeze_backbone: true
  learning_rate: 0.0015
  local_epochs: 2
  log_dir: logs
  lower_percentile: 5.0
  metadata: {}
  min_lr: 1.0e-07
  monitor_metric: val_loss
  num_classes: 1
  num_clients: 5
  num_rounds: 15
  num_workers: 10
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 4
  reduce_lr_factor: 0.5
  reduce_lr_patience: 3
  results_dir: results
  sample_fraction: 0.1
  seed: 42
  upper_percentile: 95.0
  use_custom_preprocessing: false
  use_imagenet_norm: true
  validate_images_on_init: true
  validation_split: 0.2
  weight_decay: 0.0001
constants: !!python/object:federated_pneumonia_detection.models.system_constants.SystemConstants
  BASE_PATH: .
  BATCH_SIZE: 512
  FILENAME_COLUMN: filename
  IMAGES_SUBFOLDER: Images
  IMAGE_EXTENSION: .png
  IMG_SIZE: !!python/tuple
  - 256
  - 256
  MAIN_IMAGES_FOLDER: Images
  METADATA_FILENAME: Train_metadata.csv
  PATIENT_ID_COLUMN: patientId
  SAMPLE_FRACTION: 0.1
  SEED: 42
  TARGET_COLUMN: Target
  VALIDATION_SPLIT: 0.2
custom_preprocessing_config: null
image_dir: C:\Users\User\Projects\FYP2\Training\Images
monitor_metric: val_recall
num_classes: 1
persistent_workers: false
pin_memory: true
prefetch_factor: 2
validate_images_on_init: false
